// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4079.RobotBuilderProject1.commands;
import edu.wpi.first.wpilibj.command.Command;

import java.util.ArrayList;

import org.usfirst.frc4079.RobotBuilderProject1.Robot;

/**
 *
 */
public class DriveDistance1 extends Command {
      private double distance;
      private double leftPosition, rightPosition;

      private double errorTolerance;
      private int samples;

      private ArrayList<Double> errors;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveDistance1(double distance, double duration) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.distance=distance;
        setTimeout(duration);

        errorTolerance = 5.0;
        samples = 10;

        errors = new ArrayList<Double>();
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	leftPosition=Robot.driveTrain.getLeftDistance();
    	rightPosition=Robot.driveTrain.getRightDistance();
    	Robot.driveTrain.configureForDrive();
    	
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	Robot.driveTrain.driveToTarget(leftPosition+distance, rightPosition-distance);
    	//Robot.driveTrain.drivePercentOutput(0.4, -0.4);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        double error = Math.abs(Math.abs(leftPosition - Robot.driveTrain.getLeftDistance()) - distance);

        if (errors.size() == samples) {
            errors.remove(0);
        }

        errors.add(error);

        return isRobotWithinErrorTolerance();
        //return isTimedOut();
    }

    private boolean isRobotWithinErrorTolerance() {
        double totalError = 0;

        for (double error : errors) {
            totalError += error;
        }

        double avgError = totalError / samples;

        if (avgError <= errorTolerance) {
            return true;
        }

        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
